Update README.md
harvester/harvester pull request #1118
Opened 2021-08-24 21:22 UTC by wjimenez5271

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

**Solution:**

**Related Issue:**

**Test plan:**

2021-09-01 19:31 UTC, yasker requested changes

2021-09-01 19:31 UTC, yasker commented on README.md
> +Harvester is an open source [hyper-converged infrastructure](https://en.wikipedia.org/wiki/Hyper-converged_infrastructure) (HCI) software built on Kubernetes. It is an open alternative to using a pro
Typo `ehtos`.

Also, `some of` sounds weird.

2021-09-01 19:31 UTC, yasker commented on README.md
> +We recommend server-class hardware for best results. Local workstation / laptop installs are not recommended.
Local workstation should be fine? what's the common spec for local workstation?

2021-09-02 00:28 UTC, yasker approved these changes

2021-09-02 02:18 UTC, yasker commented
@wjimenez5271 can you squash the commits into one?

2021-09-02 05:08 UTC, guangbochen approved these changes

2021-09-02 05:08 UTC, merged