Update README and docs
harvester/harvester pull request #325
Opened 2020-12-11 08:31 UTC by guangbochen

https://github.com/rancher/harvester/issues/278

2020-12-11 09:05 UTC, yzeng25 requested changes
see comments for more detals

2020-12-11 09:05 UTC, yzeng25 commented on README.md
> +| Network Switch | Equipped with at least 1 Gigabit switch, 10 Gigabit switch is recommended(Will need to enabling trunking of port for VLAN support) |
single to plural 

"10-Gigabit switches" or "10 Gigabyte switch" ?

2020-12-11 09:05 UTC, yzeng25 commented on README.md
> +### App [Development Mode]
is it necessary to emphasize "[Development Mode]" here?

2020-12-12 02:03 UTC, yasker approved these changes
LGTM.

2020-12-13 02:04 UTC, merged