fix(upgrade): make CreateImageFromISO idempotent
harvester/harvester pull request #3961
Opened 2023-05-24 09:13 UTC by starbops

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

**Solution:**

If the CreateImageFromISO is called multiple times in an upgrade, there will be multiple VMImages downloaded and associated with the same upgrade. This commit will make the function idempotent, i.e., no matter how many times it's called, there will be one and only one VMimage for the upgrade.

**Related Issue:**

#3940 

**Test plan:**

2023-05-24 09:47 UTC, w13915984028 requested changes
```
-			image, err := repo.CreateImageFromISO(version.Spec.ISOURL, version.Spec.ISOChecksum)
+			_, err = repo.CreateImageFromISOWithName(version.Spec.ISOURL, version.Spec.ISOChecksum, harvesterSystemNamespace, upgrade.Name)
 			if err != nil && !apierrors.IsAlreadyExists(err) {
 				setUpgradeCompletedCondition(toUpdate, StateFailed, corev1.ConditionFalse, err.Error(), "")
 				return h.upgradeClient.Update(toUpdate)
+			} else if err != nil && apierrors.IsAlreadyExists(err) {
+				logrus.Infof(" reuse the existing image")
 			}
-			toUpdate.Status.ImageID = fmt.Sprintf("%s/%s", image.Namespace, image.Name)

+			toUpdate.Status.ImageID = fmt.Sprintf("%s/%s", harvesterSystemNamespace, upgrade.Name)

+func (r *Repo) CreateImageFromISOWithName(isoURL string, checksum string, namespace, name string) (*harvesterv1.VirtualMachineImage, error) {
+	imageSpec := &harvesterv1.VirtualMachineImage{
+		ObjectMeta: metav1.ObjectMeta{
+			Namespace:    namespace,
+			Name: name,
+			Labels: map[string]string{
+				harvesterUpgradeLabel: r.upgrade.Name,
+			},
+			OwnerReferences: []metav1.OwnerReference{
+				upgradeReference(r.upgrade),
+			},
+		},
+		Spec: harvesterv1.VirtualMachineImageSpec{
+			DisplayName: getISODisplayNameImageName(r.upgrade.Name, r.upgrade.Spec.Version),
+			SourceType:  v1beta1.VirtualMachineImageSourceTypeDownload,
+			URL:         isoURL,
+			Checksum:    checksum,
+			Retry:       3,
+		},
+	}
+
+	return r.h.vmImageClient.Create(imageSpec)
+}
+
```

I had a draft patch yesterday, it is in another way:

Force the name of image to be same as upgrade, to avoid duplication.

Do not list from cache, just check the `create` return result, know if it is existing.

Use `list` from `local cache`  can not gurantee 100% unique ( cache has delta with api-server), given the uniquess is sured by label not namespace+name.

2023-05-30 07:10 UTC, w13915984028 approved these changes
LGTM, thanks.

2023-05-30 09:35 UTC, bk201 approved these changes
LGTM!

2023-05-30 09:36 UTC, merged

2023-05-30 09:36 UTC, bk201 commented
@mergifyio backport v1.1