Add the missing v122 v131 v132 to upgrade-matrix
harvester/harvester pull request #6626
Opened 2024-09-24 11:50 UTC by w13915984028

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

v122, v131, v132 images lists are not packet into v140 iso, the issue https://github.com/harvester/harvester/issues/5749 can not be validated.

**Solution:**

Add those missing versions to upgrade-matrix.

**Related Issue:**
https://github.com/harvester/harvester/issues/6620
https://github.com/harvester/harvester/issues/5749

**Test plan:**

via validate https://github.com/harvester/harvester/issues/6620

2024-09-24 11:50 UTC, w13915984028 commented
@mergify backport v1.4

2024-09-24 12:06 UTC, w13915984028 commented
@mergify backport v1.3

2024-09-24 12:14 UTC, bk201 commented
The file is OK on our tag commits, but reflecting the change in all branches is nice. Good spot.

2024-09-24 12:28 UTC, starbops approved these changes
LGTM, thank you.

2024-09-25 01:55 UTC, bk201 requested changes

2024-09-25 01:55 UTC, bk201 commented on package/upgrade-matrix.yaml
> +  minUpgradableVersion: v1.2.2
```suggestion
  minUpgradableVersion: v1.3.1
```

2024-09-25 01:55 UTC, bk201 commented on package/upgrade-matrix.yaml
> +  minUpgradableVersion: v1.1.2
```suggestion
  minUpgradableVersion: v1.2.1
```

2024-09-25 06:51 UTC, w13915984028 commented
@bk201 For v1.3.1, is the minUpgradableVersion v1.2.2 or v1.3.0?

2024-09-25 09:28 UTC, bk201 approved these changes

2024-09-25 09:29 UTC, bk201 commented
minVersion of 1.3.1 is 1.2.2.

2024-09-25 09:34 UTC, w13915984028 commented
Code is rebased to have additional chance to validate PR https://github.com/harvester/harvester/pull/6629 as well.

2024-09-25 10:20 UTC, merged