feat(webhook): add certs check
harvester/harvester pull request #7059
Opened 2024-11-28 08:28 UTC by FrankYang0529

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
During upgrade, if some RKE2 certs are expiration, the node upgrade may be stuck.

**Solution:**
Add certs expiration validation when users create a Upgrade CR.

**Related Issue:**
https://github.com/harvester/harvester/issues/7056

**Test plan:**
### Certs is expired in 365 days.
1. Create a version.
```
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  annotations:
    harvesterhci.io/minFreeDiskSpaceGB: "5"
    harvesterhci.io/minCertsExpirationInDay: "365"
  name: master-head
  namespace: harvester-system
spec:
  isoURL: http://192.168.0.181:8000/harvester-master-amd64.iso
  minUpgradableVersion: v1.4.0
  releaseDate: "202401231"
```
2. Create an upgrade with the version. The webhook should deny the request, because the certification will be expired in 365 days.

<img width="668" alt="Screenshot 2024-11-28 at 4 20 45 PM" src="https://github.com/user-attachments/assets/b9cecacc-0d3f-49e3-a10b-f7a4cf98d0d0">

### Certs is not expired in 7 days
1. Create a new cluster.
2. Create a version.
```
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  annotations:
    harvesterhci.io/minFreeDiskSpaceGB: "5"
  name: master-head
  namespace: harvester-system
spec:
  isoURL: http://192.168.0.181:8000/harvester-master-amd64.iso
  minUpgradableVersion: v1.4.0
  releaseDate: "202401231"
```
3. Create an upgrade with the version. It should not get any error.

2025-01-06 08:28 UTC, starbops approved these changes
LGTM, thank you.

2025-01-06 15:35 UTC, bk201 commented on pkg/webhook/resources/upgrade/validator.go
> +	earliestExpiringCert, err := util.GetEarliestExpiringCert(fmt.Sprintf("%s:443", kubernetesIP))
The code checks certs by using the service's cluster IP. If there are multiple api services behind the services, are they all checked together?

There are a lot of rotatable services in the [doc](https://docs.rke2.io/security/certificates#rotating-client-and-server-certificates-manually). Does this check cover all the services in the doc? 
> The following certificates can be rotated:
admin, api-server, controller-manager, scheduler, rke2-controller, rke2-server, cloud-controller, etcd, auth-proxy, kubelet, kube-proxy.

2025-01-13 09:16 UTC, m-ildefons requested changes
Found two small nits, but otherwise this looks good.

2025-01-13 09:16 UTC, m-ildefons commented on pkg/webhook/resources/upgrade/validator.go
> +	minCertsExpirationInDayString := "7"
If I read the code correctly, this is the default minimum time until expiration. This should be a constant and not an ad-hoc definition.

2025-01-13 09:16 UTC, m-ildefons commented on pkg/webhook/resources/upgrade/validator.go
> +			"service.name":      "kubernetes",
The fields here should be `namespace` and `name`.

2025-01-14 08:03 UTC, m-ildefons approved these changes
LGTM

2025-02-11 01:38 UTC, bk201 approved these changes

2025-02-11 02:00 UTC, merged

2025-03-07 04:55 UTC, starbops commented
@mergify backport v1.5